# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexey/Study/kloss/Lebesgue-averaging

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexey/Study/kloss/Lebesgue-averaging

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexey/Study/kloss/Lebesgue-averaging/CMakeFiles /home/alexey/Study/kloss/Lebesgue-averaging/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexey/Study/kloss/Lebesgue-averaging/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/config_parser.o: src/config_parser.cpp.o

.PHONY : src/config_parser.o

# target to build an object file
src/config_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/config_parser.cpp.o
.PHONY : src/config_parser.cpp.o

src/config_parser.i: src/config_parser.cpp.i

.PHONY : src/config_parser.i

# target to preprocess a source file
src/config_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/config_parser.cpp.i
.PHONY : src/config_parser.cpp.i

src/config_parser.s: src/config_parser.cpp.s

.PHONY : src/config_parser.s

# target to generate assembly for a file
src/config_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/config_parser.cpp.s
.PHONY : src/config_parser.cpp.s

src/endf.o: src/endf.cpp.o

.PHONY : src/endf.o

# target to build an object file
src/endf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/endf.cpp.o
.PHONY : src/endf.cpp.o

src/endf.i: src/endf.cpp.i

.PHONY : src/endf.i

# target to preprocess a source file
src/endf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/endf.cpp.i
.PHONY : src/endf.cpp.i

src/endf.s: src/endf.cpp.s

.PHONY : src/endf.s

# target to generate assembly for a file
src/endf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/endf.cpp.s
.PHONY : src/endf.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/measure.o: src/measure.cpp.o

.PHONY : src/measure.o

# target to build an object file
src/measure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/measure.cpp.o
.PHONY : src/measure.cpp.o

src/measure.i: src/measure.cpp.i

.PHONY : src/measure.i

# target to preprocess a source file
src/measure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/measure.cpp.i
.PHONY : src/measure.cpp.i

src/measure.s: src/measure.cpp.s

.PHONY : src/measure.s

# target to generate assembly for a file
src/measure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/measure.cpp.s
.PHONY : src/measure.cpp.s

src/resonances.o: src/resonances.cpp.o

.PHONY : src/resonances.o

# target to build an object file
src/resonances.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/resonances.cpp.o
.PHONY : src/resonances.cpp.o

src/resonances.i: src/resonances.cpp.i

.PHONY : src/resonances.i

# target to preprocess a source file
src/resonances.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/resonances.cpp.i
.PHONY : src/resonances.cpp.i

src/resonances.s: src/resonances.cpp.s

.PHONY : src/resonances.s

# target to generate assembly for a file
src/resonances.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/resonances.cpp.s
.PHONY : src/resonances.cpp.s

src/spectrum.o: src/spectrum.cpp.o

.PHONY : src/spectrum.o

# target to build an object file
src/spectrum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/spectrum.cpp.o
.PHONY : src/spectrum.cpp.o

src/spectrum.i: src/spectrum.cpp.i

.PHONY : src/spectrum.i

# target to preprocess a source file
src/spectrum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/spectrum.cpp.i
.PHONY : src/spectrum.cpp.i

src/spectrum.s: src/spectrum.cpp.s

.PHONY : src/spectrum.s

# target to generate assembly for a file
src/spectrum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/spectrum.cpp.s
.PHONY : src/spectrum.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/config_parser.o"
	@echo "... src/config_parser.i"
	@echo "... src/config_parser.s"
	@echo "... src/endf.o"
	@echo "... src/endf.i"
	@echo "... src/endf.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/measure.o"
	@echo "... src/measure.i"
	@echo "... src/measure.s"
	@echo "... src/resonances.o"
	@echo "... src/resonances.i"
	@echo "... src/resonances.s"
	@echo "... src/spectrum.o"
	@echo "... src/spectrum.i"
	@echo "... src/spectrum.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

